CREATE EXTERNAL TABLE IF NOT EXISTS transaction_2024.item (
    p_id bigint,
    item_id string,
    price decimal(38, 4),
    category_l1_id bigint,
    category_l1 string,
    category_l2_id bigint,
    category_l2 string,
    category_l3_id bigint,
    category_l3 string,
    category_id bigint,
    category string,
    description string,
    brand string,
    manufacturer string,
    creation_timestamp bigint,
    is_deleted boolean,
    created_date timestamp,
    updated_date timestamp,
    sync_status_id bigint,
    last_sync_date timestamp,
    sync_error_message string,
    image_url string,
    gender_target string,
    age_group string,
    item_type string,
    gp decimal(38, 4),
    weight float,
    color string,
    size string,
    origin string,
    volume string,
    material string,
    sale_status bigint,
    description_new string
)
STORED AS PARQUET
location 's3://rag-b2b-data-2024/transaction_2024/item/';